title: MathChou Homepage
description: Food for your mathematical mind
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one